version: 1.0.{build}
image: Visual Studio 2015

build_script:
- cmd: gradlew.bat build publishToMavenRepo

after_build:
- cmd: "SET PATH=C:\\Python34;C:\\Python34\\Scripts;%PATH%"

artifacts:
- path: "%USERPROFILE%/.m2/repository/com/snobot/simulator/ctre_sim_override/0.0.0"
  name: full_maven_repo
